### ISSUE TITLE
chart.removeListener is not a function after upgrade the Webpack 4 to 5

### ISSUE THREAD

**Issue by MBehtemam** [amcharts/amcharts3-react#95]
my project not a `create-react-app` project but a custom one, after we upgrade Webpack V4 to V5 and also we removed the `bable/pollyfill` this error happened. the only way to remove the error is that we should remove `listeners` from chart options. so if the the chart doesn't have `listeners` it works but if we add it again we will see this error. 
![image](https://user-images.githubusercontent.com/1811124/127436427-e2f69de5-125e-4a83-81f2-f5ee69d04f06.png)
